name: updatecli

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

permissions: {}

jobs:
  updatecli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343 # v4.0.1
        id: get_workflow_token
        with:
          application_id: ${{ vars.PAT_APPLICATION_ID }}
          application_private_key: ${{ secrets.PAT_APPLICATION_PRIVATE_KEY }}
      - uses: updatecli/updatecli-action@ca8c01bf875e2520512c344a71dd02f3dc3326a7 # v3.7.0
      - env:
          UPDATECLI_GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: updatecli apply --config updatecli.d
